import requests

from .ODataClient import ODataClient


requests.packages.urllib3.disable_warnings()


query = ODataClient('Klanten').query()
query = query.limit(2)
# query = query.order_by(Supplier.Post_Code.asc())
print(query.as_string())

for supplier in query:
    print(supplier)
    print(supplier.No)
    print(supplier.Location_Code)
    print(supplier.No)
    print(supplier.Name)
    print(supplier.Responsibility_Center)
    print(supplier.Location_Code)
    print(supplier.Post_Code)
    print(supplier.Country_Region_Code)
    print(supplier.Phone_No)
    print(supplier.IC_Partner_Code)
    print(supplier.Contact)
    print(supplier.Salesperson_Code)
    print(supplier.Customer_Posting_Group)
    print(supplier.Gen_Bus_Posting_Group)
    print(supplier.VAT_Bus_Posting_Group)
    print(supplier.Customer_Price_Group)
    print(supplier.Customer_Disc_Group)
    print(supplier.Payment_Terms_Code)
    print(supplier.Reminder_Terms_Code)
    print(supplier.Fin_Charge_Terms_Code)
    print(supplier.Currency_Code)
    print(supplier.Language_Code)
    print(supplier.Search_Name)
    print(supplier.Credit_Limit_LCY)
    print(supplier.Blocked)
    print(supplier.Privacy_Blocked)
    print(supplier.Last_Date_Modified)
    print(supplier.Application_Method)
    print(supplier.Combine_Shipments)
    print(supplier.Reserve)
    print(supplier.Ship_to_Code)
    print(supplier.Shipping_Advice)
    print(supplier.Shipping_Agent_Code)
    print(supplier.Address)
    print(supplier.City)
    print(supplier.Balance)
    print(supplier.Base_Calendar_Code)
    print(supplier.Balance_LCY)
    print(supplier.Balance_Due_LCY)
    print(supplier.Sales_LCY)
    print(supplier.Payments_LCY)
    print(supplier.Global_Dimension_1_Filter)
    print(supplier.Global_Dimension_2_Filter)
    print(supplier.Currency_Filter)
    print(supplier.Date_Filter)
